#Lab 8.2 Numpy 2D trong Python

Thời lượng ước tính cần thiết: **20** phút

## Mục tiêu

Sau khi hoàn thành lab này, bạn sẽ có thể:

-   Vận hành thoải mái với `numpy`
-   Thực hiện các phép toán phức tập với with `numpy`


<h2>Mục lục</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="create">Tạo mảng Numpy 2D</a></li>
        <li><a href="access">Truy cập các phần tử khác nhau trong Mảng Numpy</a></li>
        <li><a href="op">Các phép toán cơ bản</a></li>
    </ul>
  
</div>

<hr>


<h2 id="create">Tạo mảng Numpy 2D</h2>


In [1]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

Hãy xem xét list <code> a</code>, list chứa ba danh sách lồng nhau **có kích thước bằng nhau**.

In [2]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Chúng ta có thể truyền list vào một Mảng Numpy như sau:

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Chúng ta có thể sử dụng thuộc tính <code> ndim</code> để lấy số lượng trục hoặc chiều được coi là thứ hạng.

In [4]:
# Show the numpy array dimensions

A.ndim

2

Thuộc tính <code> shape</code> trả về tuple tương ứng với kích thước hoặc số lượng của mỗi chiều.

In [5]:
# Show the numpy array shape

A.shape

(3, 3)

Tổng số phần tử trong mảng được cung cấp bởi thuộc tính <code> size</code>.

In [6]:
# Show the numpy array size

A.size

9

<hr>


<h2 id="access">Truy cập các phần tử khác nhau của Mảng Numpy</h2>


Chúng ta có thể sử dụng dấu ngoặc vuông để truy cập các phần tử khác nhau của mảng. Sự tương ứng giữa dấu ngoặc vuông với danh sách và biểu diễn hình chữ nhật được thể hiện trong hình sau với mảng 3x3:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500" />


Chúng ta có thể truy cập vào cột thứ 2 hàng thứ 3 như trong hình sau:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400" />


Chúng ta chỉ cần sử dụng dấu ngoặc vuông và các chỉ số tương ứng với phần tử mà chúng ta muốn:

In [7]:
# Access the element on the second row and third column

A[1, 2]

23

Chúng ta cũng có thể sử dụng ký hiệu sau để lấy các phần tử:

In [8]:
# Access the element on the second row and third column

A[1][2]

23

Hãy xem xét các phần tử được hiển thị trong hình sau:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400" />


Chúng ta có thể truy cập phần tử như sau:

In [9]:
# Access the element on the first row and first column

A[0][0]

11

Chúng ta cũng có thể sử dụng slicing trong các mảng numpy. Hãy xem xét hình sau. Chúng ta muốn lấy hai cột đầu ở hàng đầu tiên.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400" />


Điều này có thể được thực hiện với cú pháp sau:

In [10]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

Tương tự, chúng ta có thể thu được hai hàng đầu tiên của cột thứ 3 như sau:

In [11]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

Tương ứng với hình sau:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="550"><br />


<h2 id="op">Các phép toán cơ bản</h2>


Chúng ta cũng có thể cộng mảng. Quá trình này giống hệt với phép cộng ma trận. Phép cộng ma trận của <code> X</code> và <code> Y</code> được hiển thị trong hình sau:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500" />


Mảng numpy được cung cấp bởi <code> X</code> và <code> Y</code>.

In [12]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [13]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

Chúng ta có thể cộng các mảng numpy như sau:

In [14]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Nhân một mảng numpy với một tỷ lệ cũng giống như nhân một ma trận với một vô hướng. Nếu nhân ma trận <code> Y</code> với hệ số vô hướng 2, chúng ta chỉ cần nhân mọi phần tử trong ma trận với 2 như trong hình.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500" />


Chúng ta có thể thực hiện thao tác tương tự trong numpy như sauz:

In [15]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [16]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Phép nhân hai mảng tương ứng với tích cặp phần tử hoặc phép nhân Hadamard. Xem xét ma trận <code> X</code> và <code> Y</code>. Phép nhân Hadamard tương ứng với việc nhân từng phần tử ở cùng một vị trí, tức là nhân các phần tử chứa trong các ô màu giống nhau với nhau. Kết quả là một ma trận mới có cùng kích thước với ma trận <code> Y</code> hoặc <code> X</code>, như trong hình sau.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500" />


Chúng ta có thể thực hiện tích cặp phần tử của mảng <code> X</code> và <code> Y</code> như sau:

In [17]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [19]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

Chúng ta cũng có thể thực hiện phép nhân ma trận với các mảng numpy <code> A</code> và <code> B</code> như sau:

Trước tiên, chúng ta xác định ma trận <code> A</code> và <code> B</code>:

In [20]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [21]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

Chúng ta sử dụng hàm numpy <code> dot</code> để nhân các mảng với nhau.

In [22]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [23]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

Chúng ta sử dụng thuộc tính numpy <code> T</code> để tính toán ma trận chuyển vị.

In [24]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [25]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

<h2>Quiz về Mảng Numpy 2D</h2>


Hãy xem xét list <code> a</code> sau, chuyển nó thành mảng Numpy.

In [26]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
A = np.array(a)
A
```

</details>


Tính kích thước mảng numpy.

In [30]:
# Write your code below and press Shift+Enter to execute
A= np.array(a)
A.size

12

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
A.size
```

</details>


Truy cập phần tử trên hàng đầu, cột đầu tiên và cột thứ hai.

In [31]:
# Write your code below and press Shift+Enter to execute
A[0][0:2]

array([1, 2])

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
A[0][0:2]
```

</details>


Thực hiện phép nhân ma trận với mảng numpy <code> A</code> và <code> B</code>.

In [33]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
Y= np.dot(A,B)
Y

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
X = np.dot(A,B)
X
```

</details>


<hr>
Nguồn: IBM
<hr>